name: Build Windows Executable

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install cx-freeze packaging requests

      - name: Build executable
        run: |
          python scripts/setup_msi.py build_exe

      - name: Build MSI installer
        run: |
          python scripts/setup_msi.py bdist_msi --target-version v0.0.0

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/
            dist/
